language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.0
    - android-21
    - extra-android-m2repository
    - extra-google-m2repository

script:
  ./gradlew build
